import "@testing-library/jest-dom/vitest";
import { cleanup } from "@testing-library/react";
import { afterEach, vi } from "vitest";

import { queryClient } from "@/app/query-client";
import { i18n } from "@/lib/i18n";

vi.mock("@tauri-apps/plugin-dialog", () => ({
  open: vi.fn(),
  save: vi.fn(),
}));

vi.mock("@/lib/tauri/pick-image", () => ({
  pickImagePath: vi.fn(),
}));

vi.mock("@/generated/tauri-bindings", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@/generated/tauri-bindings")>();
  return {
    ...actual,
    commands: {
      bootstrap: vi.fn(),
      completeOnboarding: vi.fn(),
      listMembers: vi.fn(),
      createMember: vi.fn(),
      updateMember: vi.fn(),
      archiveMember: vi.fn(),
      restoreMember: vi.fn(),
      listInstitutions: vi.fn(),
      createInstitution: vi.fn(),
      updateInstitution: vi.fn(),
      archiveInstitution: vi.fn(),
      restoreInstitution: vi.fn(),
      listGroups: vi.fn(),
      createGroup: vi.fn(),
      updateGroup: vi.fn(),
      archiveGroup: vi.fn(),
      restoreGroup: vi.fn(),
      listAccounts: vi.fn(),
      getAccount: vi.fn(),
      createAccount: vi.fn(),
      updateAccount: vi.fn(),
      updateAccountValue: vi.fn(),
      archiveAccount: vi.fn(),
      restoreAccount: vi.fn(),
      getOverview: vi.fn(),
      setMemberAvatar: vi.fn(),
      setInstitutionLogo: vi.fn(),
      setGroupLogo: vi.fn(),
      setAccountLogo: vi.fn(),
      setInstrumentLogo: vi.fn(),
      listInstruments: vi.fn(),
      getInstrument: vi.fn(),
      createInstrument: vi.fn(),
      updateInstrument: vi.fn(),
      archiveInstrument: vi.fn(),
      restoreInstrument: vi.fn(),
      listHoldings: vi.fn(),
      createHolding: vi.fn(),
      updateHolding: vi.fn(),
      archiveHolding: vi.fn(),
      restoreHolding: vi.fn(),
      listAccountCash: vi.fn(),
      appendAccountCash: vi.fn(),
      listInstrumentQuotes: vi.fn(),
      appendManualInstrumentQuote: vi.fn(),
      setInstrumentQuotePreference: vi.fn(),
      listRequiredFx: vi.fn(),
      listFxQuotes: vi.fn(),
      appendManualFxQuote: vi.fn(),
      setFxQuotePreference: vi.fn(),
      getPortfolio: vi.fn(),
      searchProviderInstruments: vi.fn(),
      refreshInstrument: vi.fn(),
      refreshRequiredFx: vi.fn(),
      refreshAll: vi.fn(),
      getMarketDataCapabilities: vi.fn(),
      backfillInstrumentHistory: vi.fn(),
      backfillRequiredFxHistory: vi.fn(),
      backfillAllHistory: vi.fn(),
      getMedia: vi.fn(),
      getSettings: vi.fn(),
      updateSettings: vi.fn(),
      deleteAllData: vi.fn(),
      getHistoryOrigin: vi.fn(),
      confirmHistoryTimezone: vi.fn(),
      previewActivity: vi.fn(),
      listActivities: vi.fn(),
      getActivity: vi.fn(),
      createActivity: vi.fn(),
      reverseActivity: vi.fn(),
      correctActivity: vi.fn(),
      getAccountTimeline: vi.fn(),
      getHistoryStatus: vi.fn(),
      rebuildHistorySnapshots: vi.fn(),
      getNetWorthTrend: vi.fn(),
      getAnalyticsStatus: vi.fn(),
      getPerformanceSummary: vi.fn(),
      getGainSummary: vi.fn(),
      listHoldingGainSummaries: vi.fn(),
      getNetWorthAttribution: vi.fn(),
      listHoldingLots: vi.fn(),
      listUnknownBasisLots: vi.fn(),
      listCostBasisDeclarations: vi.fn(),
      declareLotCostBasis: vi.fn(),
      revokeLotCostBasis: vi.fn(),
      createPendingActivity: vi.fn(),
      updatePendingActivity: vi.fn(),
      listPendingActivities: vi.fn(),
      previewPendingActivity: vi.fn(),
      postPendingActivity: vi.fn(),
      skipPendingActivity: vi.fn(),
      listRecurringActivityRules: vi.fn(),
      createRecurringActivityRule: vi.fn(),
      updateRecurringActivityRule: vi.fn(),
      archiveRecurringActivityRule: vi.fn(),
      restoreRecurringActivityRule: vi.fn(),
      generateDuePendingActivities: vi.fn(),
      createBackup: vi.fn(),
      inspectBackup: vi.fn(),
      listRecoveryBackups: vi.fn(),
      inspectRecoveryBackup: vi.fn(),
      restoreBackup: vi.fn(),
      exportCanonicalJson: vi.fn(),
      exportCsv: vi.fn(),
      previewCsvImport: vi.fn(),
      commitCsvImport: vi.fn(),
      listImportBatches: vi.fn(),
      getImportBatch: vi.fn(),
      listMaintenanceItems: vi.fn(),
      listFreshnessPolicies: vi.fn(),
      updateFreshnessPolicy: vi.fn(),
      snoozeMaintenanceItem: vi.fn(),
      listBenchmarks: vi.fn(),
      createBenchmark: vi.fn(),
      updateBenchmark: vi.fn(),
      archiveBenchmark: vi.fn(),
      restoreBenchmark: vi.fn(),
      listBenchmarkObservations: vi.fn(),
      appendBenchmarkObservation: vi.fn(),
      setDefaultBenchmark: vi.fn(),
      getBenchmarkComparison: vi.fn(),
      globalSearch: vi.fn(),
    },
  };
});

Object.defineProperty(window, "scrollTo", {
  configurable: true,
  value: () => undefined,
});

Object.defineProperty(window, "matchMedia", {
  configurable: true,
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addEventListener: () => undefined,
    removeEventListener: () => undefined,
    addListener: () => undefined,
    removeListener: () => undefined,
    dispatchEvent: () => false,
  }),
});

afterEach(() => {
  queryClient.clear();
  document.documentElement.classList.remove("dark");
  void i18n.changeLanguage("en");
  cleanup();
});
